==================================================
CNRD CRASH REPORT
==================================================

Time: 2025-04-04 19:04:34
Python version: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]

Exception details:
Type: ValueError
Message: Invalid start location ID: home

Traceback:
Traceback (most recent call last):
  File "D:\PROJECTS\CNRD PROTOTYPE\bootstrap.py", line 51, in run_game_with_error_handling
    game.main()
  File "D:\PROJECTS\CNRD PROTOTYPE\game.py", line 126, in main
    player = Player(player_name, start_location, [starter_daemon])
  File "D:\PROJECTS\CNRD PROTOTYPE\player.py", line 27, in __init__
    raise ValueError(f"Invalid start location ID: {start_location_id}")
ValueError: Invalid start location ID: home
